version: "3.7"
services:

  elasticsearch:
    build:
      context: elasticsearch/
    container_name: elasticsearch
    dns: ${DNS_HOST}
    dns_search: ${DNS_SEARCH}
    environment:
      - "node.name=es1"
      - "node.master=true"
      - "node.ml=false"
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "xpack.ml.enabled=false"
      - "cluster.name=${ELASTIC_HOST}"
      - "bootstrap.memory_lock=true"
      - "cluster.remote.connect=false"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      # - "xpack.security.http.ssl.client_authentication=optional"
      # - "xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certificates/growfam.io.privkey.pem"
      # - "xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certificates/growfam.io.bundle.pem"
    networks:
      - esnet
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
      # - ./ssl:/usr/share/elasticsearch/config/certificates:ro

        #  fluentbit:
        #    build:
        #      context: fluentbit/
        #    container_name: fluentbit
        #    depends_on:
        #      - elasticsearch
        #    networks:
        #      - esnet
        #    ports:
        #      - "5044:5044"
        #      - "5140:5140/udp"
        #      - "5140:5140"
        #      - "9600:9600"
        #    restart: unless-stopped
        #    volumes:
        #      - ./fluentbit/fluentbit-es.conf:/fluent-bit/etc/fluent-bit.conf:ro
        #      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
        #
networks:
  esnet:

volumes:
  esdata1:

