version: "3.7"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/${ES_IMAGE_NAME}:${ES_VERSION_TAG}
    container_name: elasticsearch
    environment:
      - node.name=es1
      - node.master=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - cluster.name=${ELASTIC_HOST}
      - bootstrap.memory_lock=true
      - cluster.remote.connect=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - enterpriseSearch.host=${ELASTIC_HOST}
    networks: 
      - esnet
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/esdata1:/usr/share/elasticsearch/data:rw

  fluentbit:
    image: fluent/${FLUENTBIT_IMAGE_NAME}:${FLUENTBIT_VERSION_TAG}
    container_name: fluentbit
    depends_on:
      - elasticsearch
    networks:
      - esnet
    ports:
      - "9600:9600"
      - "24224:24224"
      - "2020:2020"
    restart: unless-stopped
    volumes:
      - ./fluentbit/fluentbit-es.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro

  logstash:
    build: # image: docker.elastic.co/logstash/logstash-oss:7.10.1
      context: logstash/
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    depends_on:
      - elasticsearch
    networks:
      - esnet
    ports:
      - "5044:5044"
      - "5140:5140/udp"
      - "5140:5140"
    restart: unless-stopped
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/pipelines.yml:ro
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro

  kibana:
    image: docker.elastic.co/kibana/${KIBANA_IMAGE_NAME}:${KIBANA_VERSION_TAG}
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - elasticsearch.preserveHost=true
      - elasticsearch.startupTimeout=100000
      - elasticsearch.monitoring=false
      - elasticsearch.hosts=[${ELASTIC_HOST}]
      - kibana.index=.kibana
      - logging.dest=stdout
      - logging.silent=false
      - logging.quiet=true
      - logging.verbose=false
      - monitoring.enabled=false
      - monitoring.ui.enabled=false
      - server.host=${KIBANA_HOSTNAME}
      - server.port=${KIBANA_PORT}
      - server.name=${KIBANA_SERVER}
      - server.ssl.enabled=false
      - enterpriseSearch.host=${ELASTIC_HOST}
      # - elasticsearch.username=elastic
      # - elasticsearch.password=${ELASTIC_PASSWORD}
      # - 'elasticsearch.ssl.certificateAuthorities=["/usr/share/elasticsearch/config/certificates/ca-bundle.pem"]'
    networks:
      - esnet
    ports:
      - "127.0.0.1:5601:5601"
    restart: unless-stopped
    # volumes:
    #   - ${CA_BUNDLE}:/usr/share/elasticsearch/config/certificates/ca-bundle.pem:ro

networks:
  esnet:

