version: "3.7"
services:

  logstash:
    build: # image: docker.elastic.co/logstash/logstash-oss:7.10.1
      context: logstash/
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    networks:
      - esnet
    ports:
      - "5044:5044"
      - "5140:5140/udp"
      - "5140:5140"
      - "9600:9600"
    restart: unless-stopped
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/pipelines.yml:ro
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro
      - ./logstash/patterns:/usr/share/logstash/patterns:ro

networks:
  esnet:

