version: "3.4"
services:

  elasticsearch:
    build:
      context: elasticsearch/
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - node.master=true
      - node.ml=false
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - cluster.name=docker-elk
      - bootstrap.memory_lock=true
      - cluster.remote.connect=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - esnet
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
      - ./ssl:/etc/ssl:ro

  kibana:
    build:
      context: kibana/
    container_name: kibana
    dns: ${DNS_HOST}
    dns_search: ${DNS_SEARCH}
    environment:
      - server.host="kibana"
      - server.port="5601"
      - server.name="kibana"
      - server.ssl.enabled=false
      - kibana.index=".kibana"
      - logging.dest="stdout"
      - logging.silent=false
      - logging.quiet=true
      - logging.verbose=false
      - elasticsearch.preserveHost=true
      - elasticsearch.startupTimeout=10000
      - elasticsearch.hosts="https://${ELASTIC_HOST}:9200"
    depends_on:
      - elasticsearch
    networks:
      - esnet
    ports:
      - "127.0.0.1:5601:5601"
    restart: unless-stopped
    # volumes:
    #   - ./ssl:/etc/ssl:ro

  fluentbit:
    build:
      context: fluentbit/
    container_name: fluentbit
    depends_on:
      - elasticsearch
    networks:
      - esnet
    ports:
      - "5044:5044"
      - "5140:5140/udp"
      - "5140:5140"
      - "9600:9600"
    restart: unless-stopped
    volumes:
      - ./fluentbit/fluentbit-es.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro

networks:
  esnet:

volumes:
  esdata1:

