version: "3.7"
services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    dns: ${DNS_HOST}
    dns_search: ${DNS_SEARCH}
    environment:
      - elasticsearch.preserveHost=true
      - elasticsearch.startupTimeout=10000
      - elasticsearch.username=elastic
      - elasticsearch.password=${ELASTIC_PASSWORD}
      - elasticsearch.monitoring=false
      - elasticsearch.hosts=[${ELASTIC_HOST}]
      # - 'elasticsearch.ssl.certificateAuthorities=["/usr/share/elasticsearch/config/certificates/ca-bundle.pem"]'
      - kibana.index=.kibana
      - logging.dest=stdout
      - logging.silent=false
      - logging.quiet=true
      - logging.verbose=false
      - monitoring.enabled=false
      - monitoring.ui.enabled=false
      - server.host=kibana.growfam.io
      - server.port=5601
      - server.name=kibana
      - server.ssl.enabled=false
    networks:
      - esnet
    ports:
      - "127.0.0.1:5601:5601"
    restart: unless-stopped
    volumes:
      - ${CA_BUNDLE}:/usr/share/elasticsearch/config/certificates/ca-bundle.pem:ro
    #   - ./ssl:/etc/ssl:ro

networks:
  esnet:

volumes:
  esdata1:

